#!/bin/bash

# Read man pages in preview. Saves man pages as PostScript files which are then read by Preview. syntax: psman [command]
psman()
{
man -t "${1}" | open -f -a /Applications/Preview.app/
}

# Make a directory and move into it
mkd() {
  mkdir -p "$@"; 
  cd "$@"
}

